### Load libs required
library(Seurat)
library(dplyr)
library(cowplot)
library(ggplot2)

### Load Data
All_merge <- readRDS("~/all_merge.rds") # rds data created in DataPrep script
data_L_Alv <- read.csv("~/Mona3/Saeki_L_Alv.csv")
data_LHor <- read.csv("~/Mona3/Saeki_LHor.csv")
data_Bas <- read.csv("~/Mona3/Saeki_Basal.csv")

####Individal plots###
####

LHor_B2P0 <- AddModuleScore(B2P0_obj, features = list(data_LHor$Gene),  ctrl = 20, name= "LHor_B2P0")
#FeatureScatter(LHor_B2P0, feature1="LHor_B2P01", feature2="nFeature_RNA")
LHor_B2P0_plot <- VlnPlot(LHor_B2P0, features = c("LHor_B2P01"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LHor_B2P0_plot$data$ident <- factor(x = LHor_B2P0_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LHor_B2P0.eps", plot = LHor_B2P0_plot)
ggsave("~/ImageExports/LHor_B2P0.jpeg", plot = LHor_B2P0_plot)

LHor_B2P0HU <- AddModuleScore(B2_HU_P0_obj, features = list(data_LHor$Gene),  ctrl = 20, name= "LHor_B2P0HU")
#FeatureScatter(LHor_B2P0HU, feature1="LHor_B2P0HU1", feature2="nFeature_RNA")
LHor_B2P0HU_plot <- VlnPlot(LHor_B2P0HU, features = c("LHor_B2P0HU1"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LHor_B2P0HU_plot$data$ident <- factor(x = LHor_B2P0HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LHor_B2P0HU.eps", plot = LHor_B2P0HU_plot)
ggsave("~/ImageExports/LHor_B2P0HU.jpeg", plot = LHor_B2P0HU_plot)

LHor_B2P4HU <- AddModuleScore(B2_HU_P4_obj, features = list(data_LHor$Gene),  ctrl = 20, name= "LHor_B2P4HU")
#FeatureScatter(LHor_B2P4HU, feature1="LHor_B2P4HU1", feature2="nFeature_RNA")
LHor_B2P4HU_plot <- VlnPlot(LHor_B2P4HU, features = c("LHor_B2P4HU1"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LHor_B2P4HU_plot$data$ident <- factor(x = LHor_B2P4HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LHor_B2P4HU.eps", plot = LHor_B2P4HU_plot)
ggsave("~/ImageExports/LHor_B2P4HU.jpeg", plot = LHor_B2P4HU_plot)

LHor_B2P4 <- AddModuleScore(B2P4_obj, features = list(data_LHor$Gene),  ctrl = 20, name= "LHor_B2P4")
#FeatureScatter(LHor_B2P4, feature1="LHor_B2P41", feature2="nFeature_RNA")
LHor_B2P4_plot <- VlnPlot(LHor_B2P4, features = c("LHor_B2P41"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LHor_B2P4_plot$data$ident <- factor(x = LHor_B2P4_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LHor_B2P4.eps", plot = LHor_B2P4_plot)
ggsave("~/ImageExports/LHor_B2P4.jpeg", plot = LHor_B2P4_plot)

LHor_WTP0 <- AddModuleScore(WTP0_obj, features = list(data_LHor$Gene),  ctrl = 20, name= "LHor_WTP0")
#FeatureScatter(LHor_WTP0, feature1="LHor_WTP01", feature2="nFeature_RNA")
LHor_WTP0_plot <- VlnPlot(LHor_WTP0, features = c("LHor_WTP01"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LHor_WTP0_plot$data$ident <- factor(x = LHor_WTP0_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LHor_WTP0.eps", plot = LHor_WTP0_plot)
ggsave("~/ImageExports/LHor_WTP0.jpeg", plot = LHor_WTP0_plot)

LHor_WTP0HU <- AddModuleScore(WT_HU_P0_obj, features = list(data_LHor$Gene),  ctrl = 20, name= "LHor_WTP0HU")
#FeatureScatter(LHor_WTP0HU, feature1="LHor_WTP0HU1", feature2="nFeature_RNA")
LHor_WTP0HU_plot <- VlnPlot(LHor_WTP0HU, features = c("LHor_WTP0HU1"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LHor_WTP0HU_plot$data$ident <- factor(x = LHor_WTP0HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LHor_WTP0HU.eps", plot = LHor_WTP0HU_plot)
ggsave("~/ImageExports/LHor_WTP0HU.jpeg", plot = LHor_WTP0HU_plot)

LHor_WTP4HU <- AddModuleScore(WT_HU_P4_obj, features = list(data_LHor$Gene),  ctrl = 20, name= "LHor_WTP4HU")
#FeatureScatter(LHor_WTP4HU, feature1="LHor_WTP4HU1", feature2="nFeature_RNA")
LHor_WTP4HU_plot <- VlnPlot(LHor_WTP4HU, features = c("LHor_WTP4HU1"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LHor_WTP4HU_plot$data$ident <- factor(x = LHor_WTP4HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LHor_WTP4HU.eps", plot = LHor_WTP4HU_plot)
ggsave("~/ImageExports/LHor_WTP4HU.jpeg", plot = LHor_WTP4HU_plot)

LHor_WTP4 <- AddModuleScore(WTP4_obj, features = list(data_LHor$Gene),  ctrl = 20, name= "LHor_WTP4")
#FeatureScatter(LHor_WTP4, feature1="LHor_WTP41", feature2="nFeature_RNA")
LHor_WTP4_plot <- VlnPlot(LHor_WTP4, features = c("LHor_WTP41"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LHor_WTP4_plot$data$ident <- factor(x = LHor_WTP4_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LHor_WTP4.eps", plot = LHor_WTP4_plot)
ggsave("~/ImageExports/LHor_WTP4.jpeg", plot = LHor_WTP4_plot)

LAlv_B2P0 <- AddModuleScore(B2P0_obj, features = list(data_L_Alv$Gene),  ctrl = 20, name= "LAlv_B2P0")
#FeatureScatter(LAlv_B2P0, feature1="LAlv_B2P01", feature2="nFeature_RNA")
LAlv_B2P0_plot <- VlnPlot(LAlv_B2P0, features = c("LAlv_B2P01"),  pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LAlv_B2P0_plot$data$ident <- factor(x = LAlv_B2P0_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LAlv_B2P0.eps", plot = LAlv_B2P0_plot)
ggsave("~/ImageExports/LAlv_B2P0.jpeg", plot = LAlv_B2P0_plot)

LAlv_B2P0HU <- AddModuleScore(B2_HU_P0_obj, features = list(data_L_Alv$Gene),  ctrl = 20, name= "LAlv_B2P0HU")
#FeatureScatter(LAlv_B2P0HU, feature1="LAlv_B2P0HU1", feature2="nFeature_RNA")
LAlv_B2P0HU_plot <- VlnPlot(LAlv_B2P0HU, features = c("LAlv_B2P0HU1"),  pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LAlv_B2P0HU_plot$data$ident <- factor(x = LAlv_B2P0HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LAlv_B2P0HU.eps", plot = LAlv_B2P0HU_plot)
ggsave("~/ImageExports/LAlv_B2P0HU.jpeg", plot = LAlv_B2P0HU_plot)

LAlv_B2P4HU <- AddModuleScore(B2_HU_P4_obj, features = list(data_L_Alv$Gene),  ctrl = 20, name= "LAlv_B2P4HU")
#FeatureScatter(LAlv_B2P4HU, feature1="LAlv_B2P4HU1", feature2="nFeature_RNA")
LAlv_B2P4HU_plot <- VlnPlot(LAlv_B2P4HU, features = c("LAlv_B2P4HU1"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LAlv_B2P4HU_plot$data$ident <- factor(x = LAlv_B2P4HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LAlv_B2P4HU.eps", plot = LAlv_B2P4HU_plot)
ggsave("~/ImageExports/LAlv_B2P4HU.jpeg", plot = LAlv_B2P4HU_plot)

LAlv_B2P4 <- AddModuleScore(B2P4_obj, features = list(data_L_Alv$Gene),  ctrl = 20, name= "LAlv_B2P4")
#FeatureScatter(LAlv_B2P4, feature1="LAlv_B2P41", feature2="nFeature_RNA")
LAlv_B2P4_plot <- VlnPlot(LAlv_B2P4, features = c("LAlv_B2P41"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LAlv_B2P4_plot$data$ident <- factor(x = LAlv_B2P4_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LAlv_B2P4.eps", plot = LAlv_B2P4_plot)
ggsave("~/ImageExports/LAlv_B2P4.jpeg", plot = LAlv_B2P4_plot)

LAlv_WTP0 <- AddModuleScore(WTP0_obj, features = list(data_L_Alv$Gene),  ctrl = 20, name= "LAlv_WTP0")
#FeatureScatter(LAlv_WTP0, feature1="LAlv_WTP01", feature2="nFeature_RNA")
LAlv_WTP0_plot <- VlnPlot(LAlv_WTP0, features = c("LAlv_WTP01"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LAlv_WTP0_plot$data$ident <- factor(x = LAlv_WTP0_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LAlv_WTP0.eps", plot = LAlv_WTP0_plot)
ggsave("~/ImageExports/LAlv_WTP0.jpeg", plot = LAlv_WTP0_plot)

LAlv_WTP0HU <- AddModuleScore(WT_HU_P0_obj, features = list(data_L_Alv$Gene),  ctrl = 20, name= "LAlv_WTP0HU")
#FeatureScatter(LAlv_WTP0HU, feature1="LAlv_WTP0HU1", feature2="nFeature_RNA")
LAlv_WTP0HU_plot <- VlnPlot(LAlv_WTP0HU, features = c("LAlv_WTP0HU1"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LAlv_WTP0HU_plot$data$ident <- factor(x = LAlv_WTP0HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LAlv_WTP0HU.eps", plot = LAlv_WTP0HU_plot)
ggsave("~/ImageExports/LAlv_WTP0HU.jpeg", plot = LAlv_WTP0HU_plot)

LAlv_WTP4HU <- AddModuleScore(WT_HU_P4_obj, features = list(data_L_Alv$Gene),  ctrl = 20, name= "LAlv_WTP4HU")
#FeatureScatter(LAlv_WTP4HU, feature1="LAlv_WTP4HU1", feature2="nFeature_RNA")
LAlv_WTP4HU_plot <- VlnPlot(LAlv_WTP4HU, features = c("LAlv_WTP4HU1"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LAlv_WTP4HU_plot$data$ident <- factor(x = LAlv_WTP4HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LAlv_WTP4HU.eps", plot = LAlv_WTP4HU_plot)
ggsave("~/ImageExports/LAlv_WTP4HU.jpeg", plot = LAlv_WTP4HU_plot)

LAlv_WTP4 <- AddModuleScore(WTP4_obj, features = list(data_L_Alv$Gene),  ctrl = 20, name= "LAlv_WTP4")
#FeatureScatter(LAlv_WTP4, feature1="LAlv_WTP41", feature2="nFeature_RNA")
LAlv_WTP4_plot <- VlnPlot(LAlv_WTP4, features = c("LAlv_WTP41"), pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
LAlv_WTP4_plot$data$ident <- factor(x = LAlv_WTP4_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/LAlv_WTP4.eps", plot = LAlv_WTP4_plot)
ggsave("~/ImageExports/LAlv_WTP4.jpeg", plot = LAlv_WTP4_plot)

Bas_B2P0 <- AddModuleScore(B2P0_obj, features = list(data_Bas$Gene),  ctrl = 20, name= "Bas_B2P0")
#FeatureScatter(Bas_B2P0, feature1="Bas_B2P01", feature2="nFeature_RNA")
Bas_B2P0_plot <- VlnPlot(Bas_B2P0, features = c("Bas_B2P01"),  pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
#head(Bas_B2P0_plot$data)
Bas_B2P0_plot$data$ident <- factor(x = Bas_B2P0_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
#Bas_B2P0_plot
ggsave("~/ImageExports/Bas_B2P0.eps", plot = Bas_B2P0_plot)
ggsave("~/ImageExports/Bas_B2P0.jpeg", plot = Bas_B2P0_plot)

Bas_B2P0HU <- AddModuleScore(B2_HU_P0_obj, features = list(data_Bas$Gene),  ctrl = 20, name= "Bas_B2P0HU")
#FeatureScatter(Bas_B2P0HU, feature1="Bas_B2P0HU1", feature2="nFeature_RNA")
Bas_B2P0HU_plot <- VlnPlot(Bas_B2P0HU, features = c("Bas_B2P0HU1"),  pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
Bas_B2P0HU_plot$data$ident <- factor(x = Bas_B2P0HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/Bas_B2P0HU.eps", plot = Bas_B2P0HU_plot)
ggsave("~/ImageExports/Bas_B2P0HU.jpeg", plot = Bas_B2P0HU_plot)

Bas_B2P4HU <- AddModuleScore(B2_HU_P4_obj, features = list(data_Bas$Gene),  ctrl = 20, name= "Bas_B2P4HU")
#FeatureScatter(Bas_B2P4HU, feature1="Bas_B2P4HU1", feature2="nFeature_RNA")
Bas_B2P4HU_plot <- VlnPlot(Bas_B2P4HU, features = c("Bas_B2P4HU1"),  pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
Bas_B2P4HU_plot$data$ident <- factor(x = Bas_B2P4HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/Bas_B2P4HU.eps", plot = Bas_B2P4HU_plot)
ggsave("~/ImageExports/Bas_B2P4HU.jpeg", plot = Bas_B2P4HU_plot)

Bas_B2P4 <- AddModuleScore(B2P4_obj, features = list(data_Bas$Gene),  ctrl = 20, name= "Bas_B2P4")
#FeatureScatter(Bas_B2P4, feature1="Bas_B2P41", feature2="nFeature_RNA")
Bas_B2P4_plot <- VlnPlot(Bas_B2P4, features = c("Bas_B2P41"),  pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
Bas_B2P4_plot$data$ident <- factor(x = Bas_B2P4_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/Bas_B2P4.eps", plot = Bas_B2P4_plot)
ggsave("~/ImageExports/Bas_B2P4.jpeg", plot = Bas_B2P4_plot)

Bas_WTP0 <- AddModuleScore(WTP0_obj, features = list(data_Bas$Gene),  ctrl = 20, name= "Bas_WTP0")
#FeatureScatter(Bas_WTP0, feature1="Bas_WTP01", feature2="nFeature_RNA")
Bas_WTP0_plot <- VlnPlot(Bas_WTP0, features = c("Bas_WTP01"),  pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
Bas_WTP0_plot$data$ident <- factor(x = Bas_WTP0_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/Bas_WTP0.eps", plot = Bas_WTP0_plot)
ggsave("~/ImageExports/Bas_WTP0.jpeg", plot = Bas_WTP0_plot)

Bas_WTP0HU <- AddModuleScore(WT_HU_P0_obj, features = list(data_Bas$Gene),  ctrl = 20, name= "Bas_WTP0HU")
#FeatureScatter(Bas_WTP0HU, feature1="Bas_WTP0HU1", feature2="nFeature_RNA")
Bas_WTP0HU_plot <- VlnPlot(Bas_WTP0HU, features = c("Bas_WTP0HU1"),  pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
Bas_WTP0HU_plot$data$ident <- factor(x = Bas_WTP0HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/Bas_WTP0HU.eps", plot = Bas_WTP0HU_plot)
ggsave("~/ImageExports/Bas_WTP0HU.jpeg", plot = Bas_WTP0HU_plot)

Bas_WTP4HU <- AddModuleScore(WT_HU_P4_obj, features = list(data_Bas$Gene),  ctrl = 20, name= "Bas_WTP4HU")
#FeatureScatter(Bas_WTP4HU, feature1="Bas_WTP4HU1", feature2="nFeature_RNA")
Bas_WTP4HU_plot <- VlnPlot(Bas_WTP4HU, features = c("Bas_WTP4HU1"),  pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
Bas_WTP4HU_plot$data$ident <- factor(x = Bas_WTP4HU_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/Bas_WTP4HU.eps", plot = Bas_WTP4HU_plot)
ggsave("~/ImageExports/Bas_WTP4HU.jpeg", plot = Bas_WTP4HU_plot)

Bas_WTP4 <- AddModuleScore(WTP4_obj, features = list(data_Bas$Gene),  ctrl = 20, name= "Bas_WTP4")
#FeatureScatter(Bas_WTP4, feature1="Bas_WTP41", feature2="nFeature_RNA")
Bas_WTP4_plot <- VlnPlot(Bas_WTP4, features = c("Bas_WTP41"),  pt.size = 0.0, cols = plot_cols) + geom_boxplot(width=0.15, fill = "white") +  geom_hline(yintercept=0, linetype="dashed", color="black")
Bas_WTP4_plot$data$ident <- factor(x = Bas_WTP4_plot$data$ident, levels = c("Basal", "Basal cycling", "HR- Luminal", "HR- Luminal cycling", "HR+ Luminal"))
ggsave("~/ImageExports/Bas_WTP4.eps", plot = Bas_WTP4_plot)
ggsave("~/ImageExports/Bas_WTP4.jpeg", plot = Bas_WTP4_plot)


